### ISSUE TITLE
Sending commands causes SWG cell type to change

### ISSUE THREAD

**Issue by firstone** [cryptk/haomnilogic-local#108]
My system is normally configured for CELL-T9. Once I've installed this integration and sent some commands, cell type changed to CELL-T15 (resulting in salt level being read about half). I thought my cell had gone bad and tried replacing it. But same thing kept happening. I'd set it up, it would run until next morning when it would just change back from 9 to 15. I've disabled my schedules in HA and turned Hayward back on and it worked fine a few days. Decided to try again, send my normal schedule and right away type went to 15. This is really frustrating since 1. It affects actual chlorine generation. 2. It requires a trip to the unit to run config wizard to fix. 

This is what I've sent:

```
alias: Pool On
description: ""
trigger:
  - platform: state
    entity_id:
      - schedule.pool
    to: "on"
    from: "off"
condition: []
action:
  - type: turn_on
    device_id: e077706027761dc67414d38299c34720
    entity_id: 576d4b91b6b51237b5b5a985e12a8f56
    domain: switch
  - type: turn_on
    device_id: e077706027761dc67414d38299c34720
    entity_id: 9baf058415690a7557180754bbe6bd25
    domain: switch
  - device_id: e077706027761dc67414d38299c34720
    domain: number
    entity_id: f81af93f3e207883c6be463c835cda96
    type: set_value
    value: 60
mode: single
```

[config_entry-omnilogic_local-dc856474eb5cda5df85993e521593e46.json](https://github.com/user-attachments/files/15876908/config_entry-omnilogic_local-dc856474eb5cda5df85993e521593e46.json)
