### ISSUE TITLE
Unable to turn heater on or off with automation

### ISSUE THREAD

**Issue by firstone** [cryptk/haomnilogic-local#110]
File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 349, in async_turn_off
    await self.hass.async_add_executor_job(ft.partial(self.turn_off, **kwargs))
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 345, in turn_off
    raise NotImplementedError
NotImplementedError

**Comment by mikesalz** [comment]
What does your yaml code look like?

**Comment by firstone** [comment]
This does not work, producing result above. Same thing works fine for pump for instance.

```
device_id: e077706027761dc67414d38299c34720
domain: water_heater
entity_id: 6d7d77206fe3dae879f37261a9608c71
type: turn_off
```

This does work but it took me a while to figure out how to do. Had to check the code. Not very intuitive.

```
service: water_heater.set_operation_mode
metadata: {}
data:
  operation_mode: "off"
target:
  entity_id: water_heater.omnilogic_pool_heater
```
