### ISSUE TITLE
Set lighting effect in automation 

### ISSUE THREAD

**Issue by kr088** [cryptk/haomnilogic-local#122]
Would be great to be able to set the lighting effect when turning it on from an automation. Seems to frequently default to the last setting (?) but not consistent for me. Maybe there is a way to do this that I'm overlooking?

**Comment by nick2687** [comment]
Also would like to figure out how to set a default for this when the light is turned on. Mine always seems to revert back to voodoo lounge.

**Comment by cryptk** [comment]
This is supported as part of the light.turn_on service.  You can do it like this:

```
action: light.turn_on
target:
  entity_id: light.omnilogic_pool_color_lights
data:
  effect: COOL_CABARET
```

Just change the entity_id to be whatever your colorlogic light is.
